[package]
name = "sqlite-studio"
version = "0.1.3"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.6", features = ["derive"] }
color-eyre = "0.6.3"
include_dir = "0.7.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
tokio-rusqlite = "0.5.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
warp = "0.3.7"
open = "3.2.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
